server.port=8081
spring.application.name=gateway

spring.cloud.gateway.routes[0].id=ganaderia-api
spring.cloud.gateway.routes[0].uri=lb://ganaderia
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[1].id=ganaderia-swagger
spring.cloud.gateway.routes[1].uri=lb://ganaderia
spring.cloud.gateway.routes[1].predicates[0]=Path=/swagger-ui/**

spring.cloud.gateway.routes[2].id=ganaderia-openapi
spring.cloud.gateway.routes[2].uri=lb://ganaderia
spring.cloud.gateway.routes[2].predicates[0]=Path=/v3/api-docs/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
management.endpoints.web.exposure.include=health,info
spring.cloud.gateway.forwarded.enabled=false